### ISSUE TITLE
Justifications for threats 20,2,6,10,14

### ISSUE THREAD

**Issue by jschrack** [jschrack/CYBR-8420#70]

**Comment by MarkMagno** [comment]
Justifications completed for all threats. All are mitigated by Canvas LMS already

**Comment by MarkMagno** [comment]
Elevation by Changing the Execution Flow in Web Server  [State: Not Started]  [Priority: High]

Justification:
Implement input validation, secure coding practices, and control flow integrity to prevent unauthorized modification of the program's execution flow.

Potential Process Crash or Stop for Web Server  [State: Not Started]  [Priority: High]

Justification:
Implement input validation, resource rate limiting, and automated failover mechanisms to prevent and recover from web server crashes or slowdowns.

Spoofing the Transparent Caching Proxy External Entity  [State: Not Started]  [Priority: High]

Justification:
Implement strong authentication and validation mechanisms to verify the identity of the Transparent Caching Proxy and prevent spoofing attacks.

Spoofing of the Transparent Caching Proxy External Destination Entity  [State: Not Started]  [Priority: High]

Justification:
Implement a robust authentication mechanism, such as mutual TLS, to verify the identity of the Transparent Caching Proxy and prevent spoofing attacks.

Spoofing of Destination Data Store Application Cache  [State: Not Started]  [Priority: High]

Justification:
Implement robust authentication and validation mechanisms to ensure data is written only to the legitimate Application Cache.

**Comment by jschrack** [comment]
Justifications look good
